name: Ansible workflow
on: push

jobs:
  ansible_job:
    name: Run ansible playbook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/hello-world-docker-action@master
      with: 
        playbook: playbook-helloworld.yml
        directory: ./ansible/playbooks/helloworld