name: Ansible workflow
on: push

jobs:
  ansible_job:
    name: Run ansible playbook
    runs-on: ubuntu-latest
    steps:
    - uses: dawidd6/action-ansible-playbook@v2
      with: 
        playbook: playbook-helloworld.yml
        directory: ./ansible/playbooks/helloworld