name: Push triggered workflow
on: 
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        required: true
      workspace:
        description: Workspace
        required: true


jobs:
  my_job2:
    name: My Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Printing environment variables
        # env:
        #   ENV: dev
        #   WORKSPACE: mpp
        run: |
          echo "The environment is ${{ github.event.inputs.env }}"
          echo "The workspace is ${{ github.event.inputs.workspace }}"